backend:
  name: github
  repo: hkfrei/phvd

media_folder: src/images
public_folder: /images

collections:
  - name: angebot
    label: Angebot
    folder: src/data/angebote
    create: true
    fields:
      - { name: title, label: Title }
      - { name: type, label: Type, widget: select, options: [einzeln, gruppen] }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
