backend:
  name: github
  repo: hkfrei/phvd
# We have to upload to a static folder because there are
# path problems otherwise. Images that must not be changed
# by the cms can still live in other folders and therefore
# beeing optimised by netlify
media_folder: static/images
public_folder: /images

collections:
  - name: angebot
    label: Angebot
    folder: src/data/angebote
    create: true
    fields:
      - { name: title, label: Title }
      - { name: type, label: Type, widget: select, options: [einzeln, gruppen] }
      - { name: body, label: Body, widget: markdown }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/contact/contact.md"
        label: "Kontakt"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Foto", name: "foto", widget: "image" }
          - { label: "Telefon", name: "phone", widget: string }
          - { label: "Mail", name: "mail", widget: "string" }
          - { label: "Linkedin", name: "linkedin", widget: "string" }
